all: Server.class 

Server.class: ServerThread.class Response.class Server.java
	javac Server.java

Response.class: Pair.class Response.java
	javac Response.java

Pair.class: Pair.java
	javac Pair.java

ServerThread.class: ServerThread.java
	javac ServerThread.java
